version: "3.5"
services:
  crepe-app:
    env_file: 
      - ../.env
    build: build
    command: make run
    working_dir: /go/src/crepe
    volumes:
      - ../:/go/src/crepe
  crepe-redis:
    image: redis
    command: redis-server --appendonly yes